# Setup
title:        xmake
tagline:      A make-like build utility based on Lua
baseurl:      "/"
paginate:     1

# About/contact
author:
  name:       waruqi
  url:        http://xmake.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
